### ISSUE TITLE
verify or calculate roundoff errors

### ISSUE THREAD

**Issue by aaronmuir** [aaronmuir/Real-Linear-Optimization#11]
we are seeing roundoff errors on the branching homework problem. we need to make sure that our method to solving the system is using partial pivoting or use some other technique to reduce the round offs.

**Comment by aaronmuir** [comment]
for example, when we divide an element by itself and then subtract 1, we are getting a floating point value greater than zero. ie 1.2345e-15

**Comment by ajulovich** [comment]
Need to use java.math.BigDecimal, from what I've seen u need to use the
static method BigDecimal.valueof(number) instead of the constructor
BigDecimal(number)

**Comment by ajulovich** [comment]
It's an inherent issue with floating point math in java, I'm surprised with
your skill you haven't come across this before, there are other ways to
deal with it, but let's try BigDecimal first

**Comment by aaronmuir** [comment]
using @kiprobinson 's BigFraction https://github.com/kiprobinson/BigFraction
